In [1]:
import pandas as pd
df = pd.read_csv('../data/GlobalWeatherRepository.csv')
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [2]:
df.columns.tolist()
df.info()
df.shape()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21322 entries, 0 to 21321
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       21322 non-null  object
 1   location_name                 21322 non-null  object
 2   latitude                      21322 non-null  float64
 3   longitude                     21322 non-null  float64
 4   timezone                      21322 non-null  object
 5   last_updated_epoch            21322 non-null  int64
 6   last_updated                  21322 non-null  object
 7   temperature_celsius           21322 non-null  float64
 8   temperature_fahrenheit        21322 non-null  float64
 9   condition_text                21322 non-null  object
 10  wind_mph                      21322 non-null  float64
 11  wind_kph                      21322 non-null  float64
 12  wind_degree                   21322 non-null  int64
 13  wind_direction                21322 non-null  object
 14  pressure_mb                   21322 non-null  float64
 15  pressure_in                   21322 non-null  float64
 16  precip_mm                     21322 non-null  float64
 17  precip_in                     21322 non-null  float64
 18  humidity                      21322 non-null  int64
 19  cloud                         21322 non-null  int64
 20  feels_like_celsius            21322 non-null  float64
 21  feels_like_fahrenheit         21322 non-null  float64
 22  visibility_km                 21322 non-null  float64
 23  visibility_miles              21322 non-null  float64
 24  uv_index                      21322 non-null  float64
 25  gust_mph                      21322 non-null  float64
 26  gust_kph                      21322 non-null  float64
 27  air_quality_Carbon_Monoxide   21322 non-null  float64
 28  air_quality_Ozone             21322 non-null  float64
 29  air_quality_Nitrogen_dioxide  21322 non-null  float64
 30  air_quality_Sulphur_dioxide   21322 non-null  float64
 31  air_quality_PM2.5             21322 non-null  float64
 32  air_quality_PM10              21322 non-null  float64
 33  air_quality_us-epa-index      21322 non-null  int64
 34  air_quality_gb-defra-index    21322 non-null  int64
 35  sunrise                       21322 non-null  object
 36  sunset                        21322 non-null  object
 37  moonrise                      21322 non-null  object
 38  moonset                       21322 non-null  object
 39  moon_phase                    21322 non-null  object
 40  moon_illumination             21322 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 6.7+ MB

TypeError: 'tuple' object is not callable

In [24]:
df.shape

(21322, 41)

In [26]:
df.describe()

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,21322.000000,21322.000000,2.132200e+04,21322.000000,21322.000000,21322.000000,21322.000000,21322.000000,21322.000000,21322.000000,...,21322.000000,21322.000000,21322.000000,21322.000000,21322.000000,21322.000000,21322.000000,21322.000000,21322.000000,21322.000000
mean,19.142553,21.921348,1.720557e+09,26.441108,79.595446,8.816968,14.194091,178.640981,1012.073867,29.885837,...,21.338252,472.081906,64.679505,8.651923,5.750849,15.971677,28.412288,1.338289,1.757246,50.046853
std,24.497824,65.826545,2.817300e+06,7.066053,12.719145,13.705034,22.056780,100.699596,6.202902,0.182786,...,23.214877,1244.499338,46.428393,22.449038,70.147490,55.150608,74.132206,0.791260,1.874535,34.782359
min,-41.300000,-175.200000,1.715849e+09,-3.700000,25.300000,2.200000,3.600000,1.000000,978.000000,28.880000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.500000,0.500000,1.000000,1.000000,0.000000
25%,3.750000,-6.840000,1.718114e+09,22.900000,73.300000,4.300000,6.800000,95.000000,1009.000000,29.800000,...,12.900000,195.300000,28.300000,0.500000,0.400000,2.000000,3.700000,1.000000,1.000000,16.000000
50%,17.250000,23.320000,1.720444e+09,27.100000,80.800000,8.100000,13.000000,180.000000,1012.000000,29.900000,...,19.900000,230.300000,59.400000,1.500000,1.200000,5.000000,8.700000,1.000000,1.000000,51.000000
75%,40.400000,49.880000,1.723032e+09,30.200000,86.400000,11.900000,19.100000,260.000000,1016.000000,29.990000,...,27.400000,367.200000,94.400000,5.100000,4.100000,13.200000,24.400000,1.000000,2.000000,83.000000
max,64.150000,179.220000,1.725367e+09,49.200000,120.600000,1841.200000,2963.200000,360.000000,1045.000000,30.860000,...,2970.400000,38879.398000,480.700000,427.700000,223.200000,1614.100000,1814.400000,6.000000,10.000000,100.000000

In [28]:
df.duplicated().sum()

0

In [30]:
(df["air_quality_Carbon_Monoxide"]== -9999).sum()

1

In [32]:
(df["air_quality_Sulphur_dioxide"]== -9999).sum()

1

In [34]:
df[df['wind_mph']> 200][['country','location_name','wind_mph','wind_kph']]

      country location_name  wind_mph  wind_kph
7601  Burundi     Bujumbura    1841.2    2963.2

In [36]:
df['last_updated'].min(),

('2024-05-16 01:45',)

In [38]:
df['last_updated'].nunique()

3121

In [40]:
df['country'].nunique()

210

In [42]:
df['location_name'].nunique()

248

In [44]:
df.groupby('location_name')['last_updated'].count().describe()

count    248.000000
mean      85.975806
std       41.880486
min        1.000000
25%       88.250000
50%      109.000000
75%      110.000000
max      110.000000
Name: last_updated, dtype: float64

In [46]:
df['humidity'].min()

2

In [48]:
(df.select_dtypes(include = 'number')< 0).sum()

latitude                        4707
longitude                       5907
last_updated_epoch                 0
temperature_celsius               18
temperature_fahrenheit             0
wind_mph                           0
wind_kph                           0
wind_degree                        0
pressure_mb                        0
pressure_in                        0
precip_mm                          0
precip_in                          0
humidity                           0
cloud                              0
feels_like_celsius                43
feels_like_fahrenheit              0
visibility_km                      0
visibility_miles                   0
uv_index                           0
gust_mph                           0
gust_kph                           0
air_quality_Carbon_Monoxide        1
air_quality_Ozone                  0
air_quality_Nitrogen_dioxide       0
air_quality_Sulphur_dioxide        1
air_quality_PM2.5                  0
air_quality_PM10                   0
air_quality_us-epa-index           0
air_quality_gb-defra-index         0
moon_illumination                  0
dtype: int64

In [50]:
df['condition_text'].unique()

array(['Partly Cloudy', 'Partly cloudy', 'Sunny', 'Light drizzle',
       'Clear', 'Overcast', 'Moderate or heavy rain with thunder',
       'Patchy light rain in area with thunder', 'Fog',
       'Patchy light rain with thunder', 'Patchy rain nearby',
       'Light rain', 'Mist', 'Cloudy', 'Thundery outbreaks in nearby',
       'Moderate rain', 'Light rain shower', 'Moderate rain at times',
       'Moderate or heavy rain shower', 'Heavy rain at times',
       'Patchy light rain', 'Patchy light drizzle',
       'Thundery outbreaks possible', 'Patchy rain possible',
       'Moderate or heavy rain in area with thunder', 'Heavy rain',
       'Torrential rain shower', 'Freezing fog'], dtype=object)

In [52]:
print(df['last_updated'].max())

2024-09-04 01:30

In [54]:
df['humidity'].max()

100

In [56]:
df['wind_direction'].unique()

array(['NNW', 'NW', 'W', 'SW', 'SSE', 'E', 'N', 'SE', 'ESE', 'NNE', 'S',
       'WSW', 'SSW', 'ENE', 'NE', 'WNW'], dtype=object)

In [58]:
df = df[df['air_quality_Carbon_Monoxide'] != -9999]

In [60]:
df = df[df['air_quality_Sulphur_dioxide'] != -9999]

In [62]:
df = df[df['wind_mph']<=200]

In [64]:
df.shape

(21319, 41)

In [66]:
df['condition_text'] = df['condition_text'].str.lower()

In [68]:
df['condition_text'].nunique()

27

In [70]:
df['condition_text'].unique()

array(['partly cloudy', 'sunny', 'light drizzle', 'clear', 'overcast',
       'moderate or heavy rain with thunder',
       'patchy light rain in area with thunder', 'fog',
       'patchy light rain with thunder', 'patchy rain nearby',
       'light rain', 'mist', 'cloudy', 'thundery outbreaks in nearby',
       'moderate rain', 'light rain shower', 'moderate rain at times',
       'moderate or heavy rain shower', 'heavy rain at times',
       'patchy light rain', 'patchy light drizzle',
       'thundery outbreaks possible', 'patchy rain possible',
       'moderate or heavy rain in area with thunder', 'heavy rain',
       'torrential rain shower', 'freezing fog'], dtype=object)

In [72]:
location_counts = df['location_name'].value_counts()
location_counts

location_name
Kabul               110
Berlin              110
Budapest            110
Vatican City        110
Port-Au-Prince      110
                   ...
Tripoli               1
Male                  1
Bali                  1
Palau                 1
Ho Chi Minh City      1
Name: count, Length: 248, dtype: int64

In [74]:
valid_locations = location_counts[location_counts>20].index
valid_locations

Index(['Kabul', 'Berlin', 'Budapest', 'Vatican City', 'Port-Au-Prince',
       'Georgetown', 'Bissau', 'Conakry', 'Moscow', 'Basseterre',
       ...
       'Ngaoundere', 'Dhidhdhoo', 'Ban Lom', 'Koror', 'Lom', 'Norman Gardens',
       'Grindavik', 'Felidhoo', 'Pasto', 'Rangoon'],
      dtype='object', name='location_name', length=201)

In [76]:
df = df[df['location_name'].isin(valid_locations)]
df.shape

(21106, 41)

In [78]:
df['location_name'].nunique()

201